version: "3.7"
services:
  datascience-notebook:
      image: jupyter/datascience-notebook
      volumes:
        - /Users:/home/jovyan/work
      ports:
        - 8888:8888
      container_name:   datascience-notebook-container
